sudo: false
dist: trusty
language: python
python:
  - 2.7
  - 3.5
  - 3.6
cache: pip
install:
  - pip install -U pip wheel
  - pip install -U tensorflow==1.3.0rc2
  - pip install -U --process-dependency-links .
  - pip install -U .[test]
  - pip install -U codecov
script:
  - nosetests testing
after_success:
  - codecov
